package ffxiv.fisher.model;

public enum Location {
	
	// ===== La Noscea =====
	
	// Limsa Lominsa Upper Decks
	LIMSA_LOMINSA_UPPER_DECKS(Area.LIMSA_LOMINSA_UPPER_DECKS),
	
	// Limsa Lominsa Lower Decks
	LIMSA_LOMINSA_LOWER_DECKS(Area.LIMSA_LOMINSA_LOWER_DECKS),
	
	// Middle La Noscea
	ZEPHYR_DRIFT(Area.MIDDLE_LA_NOSCEA),
	ROGUE_RIVER(Area.MIDDLE_LA_NOSCEA),
	WEST_AGELYSS_RIVER(Area.MIDDLE_LA_NOSCEA),
	SUMMERFORD(Area.MIDDLE_LA_NOSCEA),
	NYM_RIVER(Area.MIDDLE_LA_NOSCEA),
	WOAD_WHISPER_CANYON(Area.MIDDLE_LA_NOSCEA),
	
	// Lower La Noscea
    THE_MOURNING_WIDOW(Area.LOWER_LA_NOSCEA),
    MORABY_BAY(Area.LOWER_LA_NOSCEA),
    CEDARWOOD(Area.LOWER_LA_NOSCEA),
    MORABY_DRYDOCKS(Area.LOWER_LA_NOSCEA),
    OSCHONS_TORCH(Area.LOWER_LA_NOSCEA),
    THE_SALT_STRAND(Area.LOWER_LA_NOSCEA),
    CANDLEKEEP_QUAY(Area.LOWER_LA_NOSCEA),
    EMPTY_HEART(Area.LOWER_LA_NOSCEA),
    BLIND_IRON_MINES(Area.LOWER_LA_NOSCEA),
    
    // Eastern La Noscea
    SOUTH_BLOODSHORE(Area.EASTERN_LA_NOSCEA),
    COSTA_DEL_SOL(Area.EASTERN_LA_NOSCEA),
    NORTH_BLOODSHORE(Area.EASTERN_LA_NOSCEA),
    HIDDEN_FALLS(Area.EASTERN_LA_NOSCEA),
    EAST_AGELYSS_RIVER(Area.EASTERN_LA_NOSCEA),
    RAINCATCHER_GULLY(Area.EASTERN_LA_NOSCEA),
    THE_JUGGERNAUT(Area.EASTERN_LA_NOSCEA),
    RED_MANTIS_FALLS(Area.EASTERN_LA_NOSCEA),
    
    // Western La Noscea
    SWIFTPERCH(Area.WESTERN_LA_NOSCEA),
    SKULL_VALLEY(Area.WESTERN_LA_NOSCEA),
    HALFSTONE(Area.WESTERN_LA_NOSCEA),
    NORTH_UMBRAL_ISLES(Area.WESTERN_LA_NOSCEA),
    SOUTH_UMBRAL_ISLES(Area.WESTERN_LA_NOSCEA),
    THE_BREWERS_BEACON(Area.WESTERN_LA_NOSCEA),
    THE_SHIP_GRAVEYARD(Area.WESTERN_LA_NOSCEA),
    SAPSA_SPAWNING_GROUNDS(Area.WESTERN_LA_NOSCEA),
    REAVER_HIDE(Area.WESTERN_LA_NOSCEA),

    // Upper La Noscea
    OAKWOOD(Area.UPPER_LA_NOSCEA),
    FOOL_FALLS(Area.UPPER_LA_NOSCEA),
    NORTH_BRONZE_LAKE(Area.UPPER_LA_NOSCEA),
    BRONZE_LAKE_SHALLOWS(Area.UPPER_LA_NOSCEA),

    // Outer La Noscea
    THE_LONG_CLIMB(Area.OUTER_LA_NOSCEA),
    
    // Mist
    MIST(Area.MIST),
    
    // ===== The Black Shroud =====
    
    // New Gridania
    JADEITE_FLOOD(Area.NEW_GRIDANIA),
    LOWER_BLACK_TEA_BROOK(Area.NEW_GRIDANIA),
    
    // Old Gridania
    WHISPERING_GORGE(Area.OLD_GRIDANIA),
    UPPER_BLACK_TEA_BROOK(Area.OLD_GRIDANIA),
    
    // Central Shroud
    THE_VEIN(Area.CENTRAL_SHROUD),
    THE_MIRROR(Area.CENTRAL_SHROUD),
    EVERSCHADE(Area.CENTRAL_SHROUD),
    HOPESEED_POND(Area.CENTRAL_SHROUD),
    HAUKKE_MANOR(Area.CENTRAL_SHROUD),
    
    // East Shroud
    SWEETBLOOM_PIER(Area.EAST_SHROUD),
    VERDANT_DROP(Area.EAST_SHROUD),
    SPRINGGRIPPLE_BROOK(Area.EAST_SHROUD),
    SYLPHLANDS(Area.EAST_SHROUD),
    SANCTUM_OF_THE_TWELVE(Area.EAST_SHROUD),
    
    // South Shroud
    UPPER_HATHOEVA_RIVER(Area.SOUTH_SHROUD),
    MIDDLE_HATHOEVA_RIVER(Area.SOUTH_SHROUD),
    LOWER_HATHOEVA_RIVER(Area.SOUTH_SHROUD),
    EAST_HATHOEVA_RIVER(Area.SOUTH_SHROUD),
    GOBLINBLOOD(Area.SOUTH_SHROUD),
    ROOTSLAKE(Area.SOUTH_SHROUD),
    URTHS_GIFT(Area.SOUTH_SHROUD),
    
    // North Shroud
    MURMUR_RILLS(Area.NORTH_SHROUD),
    FALLGOURD_FLOAT(Area.NORTH_SHROUD),
    PROUD_CREEK(Area.NORTH_SHROUD),
    LAKE_TAHTOTL(Area.NORTH_SHROUD),
    
    // Lavender Beds
    LAVENDER_BEDS(Area.LAVENDER_BEDS),
    
    // ===== Thanalan =====
    
    // Western Thanalan
    THE_SILVER_BAZAAR(Area.WESTERN_THANALAN),
    VESPER_BAY(Area.WESTERN_THANALAN),
    CRESCENT_COVE(Area.WESTERN_THANALAN),
    NOPHICAS_WELLS(Area.WESTERN_THANALAN),
    THE_FOOTFALLS(Area.WESTERN_THANALAN),
    CAPE_WESTWIND(Area.WESTERN_THANALAN),
    PARATAS_PEACE(Area.WESTERN_THANALAN),
    MOONDRIP(Area.WESTERN_THANALAN),
    
    // Central Thanalan
    UPPER_SOOT_CREEK(Area.CENTRAL_THANALAN),
    LOWER_SOOT_CREEK(Area.CENTRAL_THANALAN),
    THE_UNHOLY_HEIR(Area.CENTRAL_THANALAN),
    THE_CLUTCH(Area.CENTRAL_THANALAN),
    
    // Eastern Thanalan
    NORTH_DRYBONE(Area.EASTERN_THANALAN),
    SOUTH_DRYBONE(Area.EASTERN_THANALAN),
    YUGRAM_RIVER(Area.EASTERN_THANALAN),
    THE_BURNING_WALL(Area.EASTERN_THANALAN),
    
    // Southern Thanalan
    BURNT_LIZARD_CREEK(Area.SOUTHERN_THANALAN),
    ZAHARAK(Area.SOUTHERN_THANALAN),
    FORGOTTEN_SPRINGS(Area.SOUTHERN_THANALAN),
    SAGOLII_DESERT(Area.SOUTHERN_THANALAN),
    SAGOLII_DUNES(Area.SOUTHERN_THANALAN),
    
    // Northern Thanalan
    CERULEUM_FIELD(Area.NORTHERN_THANALAN),
    BLUEFOG(Area.NORTHERN_THANALAN),
    
    // The Goblet
    THE_GOBLET(Area.THE_GOBLET),
    
    // ===== Coerthas =====
    
    // Coerthas Central Highlands
    COERTHAS_RIVER(Area.COERTHAS_CENTRAL_HIGHLANDS),
    WITCHDROP(Area.COERTHAS_CENTRAL_HIGHLANDS),
    THE_NAIL(Area.COERTHAS_CENTRAL_HIGHLANDS),
    THE_WEEPING_SAINT(Area.COERTHAS_CENTRAL_HIGHLANDS),
    DRAGONHEAD_LATRINES(Area.COERTHAS_CENTRAL_HIGHLANDS),
    DANIFFEN_PASS(Area.COERTHAS_CENTRAL_HIGHLANDS),
    EXPLORATORY_ICE_HOLE(Area.COERTHAS_CENTRAL_HIGHLANDS),
    SNOWCLOAK(Area.COERTHAS_CENTRAL_HIGHLANDS),
    SEA_OF_CLOUDS(Area.COERTHAS_CENTRAL_HIGHLANDS),
    
    // ===== Mor Dhona =====
    
    // Mor Dhona
    NORTH_SILVERTEAR(Area.MOR_DHONA),
    RATHEFROST(Area.MOR_DHONA),
    THE_TANGLE(Area.MOR_DHONA),
    THE_DEEP_TANGLE(Area.MOR_DHONA),
    SINGING_SHARDS(Area.MOR_DHONA),
    THE_NORTH_SHARDS(Area.MOR_DHONA);
	
	private final Area area;
	
	private Location(Area area) {
		this.area = area;
	}
	
	public Area getArea() {
		return area;
	}
}
