package ffxiv.fisher.model;

public enum Location {
	
	// ===== La Noscea =====
	
	// Limsa Lominsa Upper Decks
	LIMSA_LOMINSA_UPPER_DECKS(Area.LIMSA_LOMINSA_UPPER_DECKS, 10101),
	
	// Limsa Lominsa Lower Decks
	LIMSA_LOMINSA_LOWER_DECKS(Area.LIMSA_LOMINSA_LOWER_DECKS, 10201),
	
	// Middle La Noscea
	ZEPHYR_DRIFT(Area.MIDDLE_LA_NOSCEA, 10301),
	SUMMERFORD(Area.MIDDLE_LA_NOSCEA, 10302),
	ROGUE_RIVER(Area.MIDDLE_LA_NOSCEA, 10303),
	WEST_AGELYSS_RIVER(Area.MIDDLE_LA_NOSCEA, 10304),
	NYM_RIVER(Area.MIDDLE_LA_NOSCEA, 10305),
	WOAD_WHISPER_CANYON(Area.MIDDLE_LA_NOSCEA, 10306),
	
	// Lower La Noscea
    THE_MOURNING_WIDOW(Area.LOWER_LA_NOSCEA, 10401),
    MORABY_BAY(Area.LOWER_LA_NOSCEA, 10402),
    CEDARWOOD(Area.LOWER_LA_NOSCEA, 10403),
    MORABY_DRYDOCKS(Area.LOWER_LA_NOSCEA, 10404),
    OSCHONS_TORCH(Area.LOWER_LA_NOSCEA, 10405),
    THE_SALT_STRAND(Area.LOWER_LA_NOSCEA, 10406),
    CANDLEKEEP_QUAY(Area.LOWER_LA_NOSCEA, 10407),
    EMPTY_HEART(Area.LOWER_LA_NOSCEA, 10408),
    BLIND_IRON_MINES(Area.LOWER_LA_NOSCEA, 10409),
    
    // Eastern La Noscea
    SOUTH_BLOODSHORE(Area.EASTERN_LA_NOSCEA, 10501),
    COSTA_DEL_SOL(Area.EASTERN_LA_NOSCEA, 10502),
    NORTH_BLOODSHORE(Area.EASTERN_LA_NOSCEA, 10503),
    HIDDEN_FALLS(Area.EASTERN_LA_NOSCEA, 10504),
    EAST_AGELYSS_RIVER(Area.EASTERN_LA_NOSCEA, 10505),
    RAINCATCHER_GULLY(Area.EASTERN_LA_NOSCEA, 10506),
    THE_JUGGERNAUT(Area.EASTERN_LA_NOSCEA, 10507),
    RED_MANTIS_FALLS(Area.EASTERN_LA_NOSCEA, 10508),
    RHOTANO_SEA_FORECASTLE(Area.EASTERN_LA_NOSCEA, 10509),
    RHOTANO_SEA_STERNCASTLE(Area.EASTERN_LA_NOSCEA, 10510),
    
    // Western La Noscea
    SWIFTPERCH(Area.WESTERN_LA_NOSCEA, 10601),
    SKULL_VALLEY(Area.WESTERN_LA_NOSCEA, 10602),
    HALFSTONE(Area.WESTERN_LA_NOSCEA, 10603),
    NORTH_UMBRAL_ISLES(Area.WESTERN_LA_NOSCEA, 10604),
    SOUTH_UMBRAL_ISLES(Area.WESTERN_LA_NOSCEA, 10605),
    THE_BREWERS_BEACON(Area.WESTERN_LA_NOSCEA, 10606),
    THE_SHIP_GRAVEYARD(Area.WESTERN_LA_NOSCEA, 10607),
    SAPSA_SPAWNING_GROUNDS(Area.WESTERN_LA_NOSCEA, 10608),
    REAVER_HIDE(Area.WESTERN_LA_NOSCEA, 10609),

    // Upper La Noscea
    OAKWOOD(Area.UPPER_LA_NOSCEA, 10701),
    FOOL_FALLS(Area.UPPER_LA_NOSCEA, 10702),
    NORTH_BRONZE_LAKE(Area.UPPER_LA_NOSCEA, 10703),
    BRONZE_LAKE_SHALLOWS(Area.UPPER_LA_NOSCEA, 10704),

    // Outer La Noscea
    THE_LONG_CLIMB(Area.OUTER_LA_NOSCEA, 10801),
    
    // Mist
    MIST(Area.MIST, 10901),
    
    // ===== The Black Shroud =====
    
    // New Gridania
    JADEITE_FLOOD(Area.NEW_GRIDANIA, 20101),
    LOWER_BLACK_TEA_BROOK(Area.NEW_GRIDANIA, 20102),
    
    // Old Gridania
    WHISPERING_GORGE(Area.OLD_GRIDANIA, 20201),
    UPPER_BLACK_TEA_BROOK(Area.OLD_GRIDANIA, 20202),
    
    // Central Shroud
    THE_VEIN(Area.CENTRAL_SHROUD, 20301),
    THE_MIRROR(Area.CENTRAL_SHROUD, 20302),
    EVERSCHADE(Area.CENTRAL_SHROUD, 20303),
    HOPESEED_POND(Area.CENTRAL_SHROUD, 20304),
    HAUKKE_MANOR(Area.CENTRAL_SHROUD, 20305),
    
    // East Shroud
    SWEETBLOOM_PIER(Area.EAST_SHROUD, 20401),
    VERDANT_DROP(Area.EAST_SHROUD, 20402),
    SPRINGGRIPPLE_BROOK(Area.EAST_SHROUD, 20403),
    SYLPHLANDS(Area.EAST_SHROUD, 20404),
    SANCTUM_OF_THE_TWELVE(Area.EAST_SHROUD, 20405),
    
    // South Shroud
    UPPER_HATHOEVA_RIVER(Area.SOUTH_SHROUD, 20501),
    MIDDLE_HATHOEVA_RIVER(Area.SOUTH_SHROUD, 20502),
    LOWER_HATHOEVA_RIVER(Area.SOUTH_SHROUD, 20503),
    EAST_HATHOEVA_RIVER(Area.SOUTH_SHROUD, 20504),
    GOBLINBLOOD(Area.SOUTH_SHROUD, 20505),
    ROOTSLAKE(Area.SOUTH_SHROUD, 20506),
    URTHS_GIFT(Area.SOUTH_SHROUD, 20507),
    
    // North Shroud
    MURMUR_RILLS(Area.NORTH_SHROUD, 20601),
    FALLGOURD_FLOAT(Area.NORTH_SHROUD, 20602),
    PROUD_CREEK(Area.NORTH_SHROUD, 20603),
    LAKE_TAHTOTL(Area.NORTH_SHROUD, 20604),
    
    // Lavender Beds
    LAVENDER_BEDS(Area.LAVENDER_BEDS, 20701),
    
    // ===== Thanalan =====
    
    // Western Thanalan
    THE_SILVER_BAZAAR(Area.WESTERN_THANALAN, 30101),
    VESPER_BAY(Area.WESTERN_THANALAN, 30102),
    CRESCENT_COVE(Area.WESTERN_THANALAN, 30103),
    NOPHICAS_WELLS(Area.WESTERN_THANALAN, 30104),
    THE_FOOTFALLS(Area.WESTERN_THANALAN, 30105),
    CAPE_WESTWIND(Area.WESTERN_THANALAN, 30106),
    PARATAS_PEACE(Area.WESTERN_THANALAN, 30107),
    MOONDRIP(Area.WESTERN_THANALAN, 30108),
    
    // Central Thanalan
    UPPER_SOOT_CREEK(Area.CENTRAL_THANALAN, 30201),
    LOWER_SOOT_CREEK(Area.CENTRAL_THANALAN, 30202),
    THE_UNHOLY_HEIR(Area.CENTRAL_THANALAN, 30203),
    THE_CLUTCH(Area.CENTRAL_THANALAN, 30204),
    
    // Eastern Thanalan
    NORTH_DRYBONE(Area.EASTERN_THANALAN, 30301),
    SOUTH_DRYBONE(Area.EASTERN_THANALAN, 30302),
    YUGRAM_RIVER(Area.EASTERN_THANALAN, 30303),
    THE_BURNING_WALL(Area.EASTERN_THANALAN, 30304),
    
    // Southern Thanalan
    BURNT_LIZARD_CREEK(Area.SOUTHERN_THANALAN, 30401),
    ZAHARAK(Area.SOUTHERN_THANALAN, 30402),
    FORGOTTEN_SPRINGS(Area.SOUTHERN_THANALAN, 30403),
    SAGOLII_DESERT(Area.SOUTHERN_THANALAN, 30404),
    SAGOLII_DUNES(Area.SOUTHERN_THANALAN, 30405),
    
    // Northern Thanalan
    CERULEUM_FIELD(Area.NORTHERN_THANALAN, 30501),
    BLUEFOG(Area.NORTHERN_THANALAN, 30502),
    
    // The Goblet
    THE_GOBLET(Area.THE_GOBLET, 30601),
    
    // ===== Coerthas =====
    
    // Coerthas Central Highlands
    COERTHAS_RIVER(Area.COERTHAS_CENTRAL_HIGHLANDS, 40101),
    WITCHDROP(Area.COERTHAS_CENTRAL_HIGHLANDS, 40102),
    THE_NAIL(Area.COERTHAS_CENTRAL_HIGHLANDS, 40103),
    THE_WEEPING_SAINT(Area.COERTHAS_CENTRAL_HIGHLANDS, 40104),
    DRAGONHEAD_LATRINES(Area.COERTHAS_CENTRAL_HIGHLANDS, 40105),
    DANIFFEN_PASS(Area.COERTHAS_CENTRAL_HIGHLANDS, 40106),
    EXPLORATORY_ICE_HOLE(Area.COERTHAS_CENTRAL_HIGHLANDS, 40107),
    SNOWCLOAK(Area.COERTHAS_CENTRAL_HIGHLANDS, 40108),
    SEA_OF_CLOUDS(Area.COERTHAS_CENTRAL_HIGHLANDS, 40109),
    
    // ===== Mor Dhona =====
    
    // Mor Dhona
    NORTH_SILVERTEAR(Area.MOR_DHONA, 50101),
    RATHEFROST(Area.MOR_DHONA, 50102),
    THE_TANGLE(Area.MOR_DHONA, 50103),
    THE_DEEP_TANGLE(Area.MOR_DHONA, 50104),
    SINGING_SHARDS(Area.MOR_DHONA, 50105),
    THE_NORTH_SHARDS(Area.MOR_DHONA, 50106);
	
	
	
	private final Area area;
	private final int cbhId;
	
	private Location(Area area, int cbhId) {
		this.area = area;
		this.cbhId = cbhId;
	}
	
	public Area getArea() {
		return area;
	}
	
	public int getCbhId() {
		return cbhId;
	}
}
